Feature/acs 2106 an 7792 bulletin constant supports
placetopay/mpi pull request #16
Opened 2024-02-08 20:55 UTC by alejandroramirez-eve

2024-02-15 22:55 UTC, mcotesm requested changes

2024-02-15 22:55 UTC, mcotesm commented on src/Requests/Fields/ThreeDSAuthenticationIndForFranchise.php
> +        if (self::isPaymentRequestForAgentPayment($data)
Se puede separar esto en métodos privados para que sea más legible.  Por ejemplo, la segunda validación podría ser validateIndicator.

2024-02-15 22:55 UTC, mcotesm commented on src/Requests/Fields/ThreeDSAuthenticationIndForFranchise.php
> +        if (self::isPaymentUnknownOrUndefinedFinalAmount($data)
Aquí podemos hacer lo mismo que el anterior

2024-02-15 22:55 UTC, mcotesm commented on src/Requests/Fields/ThreeRIIndForFranchise.php
> +        if (self::isPaymentRequestForAgentPayment($data)
Mismo consejo que la anterior clase

2024-02-15 22:55 UTC, mcotesm commented on src/Requests/Fields/ThreeRIIndForFranchise.php
> +        if (self::isPaymentUnknownOrUndefinedFinalAmount($data)
Mismo consejo

2024-02-19 20:14 UTC, mcotesm approved these changes

2024-02-22 12:49 UTC, freddiegar approved these changes

2024-07-05 21:47 UTC, closed without merging