WIP Feature/added new 3dsmpi version
placetopay/mpi pull request #3
Opened 2020-03-16 16:21 UTC by davidv99

2020-04-06 22:11 UTC, eduarguz commented on src/Clients/MockClientVersionOne.php
> +    public function loockup($url, $method, $data, $headers): array
use `lookup`

2020-04-06 22:11 UTC, eduarguz commented on src/Constants/MPI.php
> +    const THREEDS_AUTH_IND = [
del nombre `THREEDS_AUTH_IND` no me queda claro qué es `ind` algunas veces es mejor ser explicito, podemos usar `THREEDS_AUTH_INDICATOR` (asumiendo que es indicator)

2020-04-06 22:11 UTC, eduarguz commented on src/Constants/MPI.php
> +    const PAYMENT_TX_CODE = '01';
del nombre `PAYMENT_TX_CODE` es claro que TX significa `TRANSACTION`, pero es necesaria la abstracción?
Pienso que es más entendible y directo `PAYMENT_TRANSACTION_CODE` lo mismo aplica para los otros TX

2020-04-06 22:11 UTC, eduarguz commented on src/Entities/MpiContract.php
> +    public function lookupEndpoint();
puedes "organizar" la interfaz que quede como agrupada

lookup
lookupResponse
lookupEndpoint
queryEndpoint
queryResponse

2020-04-06 22:11 UTC, eduarguz commented on src/Entities/MpiManager.php
> +    public static function create(string $version)
Creo que hay casos conde podemos aprovechar los tipos de retorno tambien 

en este caso siempre se espera un tipo `MPIContract`

2020-04-06 22:11 UTC, eduarguz commented on src/Entities/VersionTwoMpi.php
> +        return new LookUpVersionTwoRequest($data);
Si te fijas en la forma en la que estamos nombrando algunas clases 
En la respuesta del lookup se llama:
`lookupResponseVersionTwo`
pero el request se llama:
`LookupVersionTwoRequest`

La palabra Request y Response de alguna forma van conectadas, y en los nombres se aprecia que no siguen una estructura, deberían tener nombres como 
`LookupResponseVersionOne`
`LookupRequestVersionOne`

Revisar los otros nombres por si hay algo parecido

2020-04-06 22:11 UTC, eduarguz commented on src/MPIService.php
> +    private $versionDirector;
podemos ponerle otro nombre a esta clase, todavia me queda ese `Director` que no encaja mucho en la responsabilidad 

algunas ideas 
`versionManager`
`versionMessage`
`mpiManager`

2020-04-13 23:13 UTC, dnetix commented on src/Clients/MockClientVersionOne.php
> +            case '4532840681197602':
Trata de homologar las tarjetas de prueba a que tengan el mismo comportamiento y que sean las mismas en ambas versiones

2020-04-13 23:15 UTC, dnetix commented on src/Clients/MockClientVersionTwo.php
> +                ];
En el mock que había que ahora es v1 la forma en que se asigna el transactionID, que luego se traduce en el ID por el cúal se hará el query se selecciona mediante el mes de expiración, de esta manera si mando por ejemplo 01/21 el id es 1 y la respuesta del query es aceptada, si mando 02/21 la respuesta del query para el transaction id 2 es rechazada, etc. Por eso la homologación y procura añadir este comportamiento a este mock y en el readme

2020-04-13 23:23 UTC, dnetix requested changes

2020-04-13 23:23 UTC, dnetix commented on src/Contracts/LookupResponse.php
> +    abstract function processUrl(): string;
A este contrato le añadiría "version" para que me retorne de que versión de 3DS y el extra que retorne el arreglo

2020-04-13 23:23 UTC, dnetix commented on src/Contracts/QueryResponse.php
> +
Añadir "version" tambien

2020-04-13 23:23 UTC, dnetix commented on src/Entities/MpiContract.php
> +    public function lookup(array $data);
Añadir los tipos de retorno, y una corta descripción de que harían esas funciones, sobre todo porque no entiendo la diferencia en lookup y lookupResponse

2020-04-13 23:23 UTC, dnetix commented on src/Entities/MpiManager.php
> +        throw new \Exception('Wrong version provided for lookup methods');
Trata de manejar excepciones de la librería, si sale un \Exception de acá sería como si no se hubiera manejado o no se supiera por qué pasó

2020-04-13 23:23 UTC, dnetix commented on src/Messages/LookupResponseVersionTwo.php
> +    public function toArray()
Añadir tambien el tipo de retorno

2020-04-14 21:28 UTC, davidv99 commented on src/Contracts/LookupResponse.php
> +    abstract function processUrl(): string;
Actualizado

2020-04-14 21:28 UTC, davidv99 commented on src/Contracts/QueryResponse.php
> +
Actualizado

2020-04-14 21:28 UTC, davidv99 commented on src/Entities/MpiContract.php
> +    public function lookup(array $data);
Actualizado

2020-04-14 21:29 UTC, davidv99 commented on src/Entities/MpiManager.php
> +        throw new \Exception('Wrong version provided for lookup methods');
Actualizado a MPIException

2020-04-14 21:29 UTC, davidv99 commented on src/Messages/LookupResponseVersionTwo.php
> +    public function toArray()
actualizado

2020-04-14 21:32 UTC, davidv99 commented on src/Clients/MockClientVersionTwo.php
> +                ];
Se añadió la validación que me sugeriste para la obtención del id de la transacción en base a la fecha ingresada, sin embargo se hizo tomando como id de la transacción el mes que se ingresa en la fecha de expiración de la tarjeta, teniendo como posibles valores de respuesta del 1  - 6, me queda la duda es si ¿puede ser bueno implementar un valor default para el caso que no aplique algunos de los meses ingresados?

2020-04-14 21:34 UTC, davidv99 commented on src/Clients/MockClientVersionOne.php
> +            case '4532840681197602':
El comportamiento cambia un poco debido a los atributos que se reciben para el método lookup en la v1 y la v2, sin embargo se hizo una homologación de tarjetas y se actualizaron los casos para devolver las respuestas o comportamientos similares en la v2

2020-05-05 16:23 UTC, dnetix approved these changes

2020-05-05 16:25 UTC, merged